### ISSUE TITLE
Remove the OCA Explorer application

### ISSUE THREAD

**Issue by amanji** [bcgov/aries-oca-bundles#107]
OCA Explorer has been migrated to its own repo at [bcgov/aries-oca-explorer](https://github.com/bcgov/aries-oca-explorer). This ticket tracks the following tasks:

- [x] Remove the OCA Explorer application from this repo
- [x] Remove the associated GH action to deploy to GH pages
- [ ] (Optional) rename the `OCABundles` directory. (@swcurran if this step is unnecessary we can skip it)

**Comment by swcurran** [comment]
I recall talking about the need to rename the OCABundles repo. Remind me about that?

**Comment by amanji** [comment]
Should we just rename the folder to `bundles`?

**Comment by swcurran** [comment]
I don’t think so.  It doesn’t really matter….
