### ISSUE TITLE
GHA to validate OCABundle.json on opened PRs

### ISSUE THREAD

**Issue by esune** [bcgov/aries-oca-bundles#59]
GitHub action to be executed on opened PRs as check to validate the `OCABundle.json` to be added to the repository is - at least - syntactically correct (using a schema validator).

Acceptance Criteria:
- When a PR is opened, the action will check for the existence of a `OCABundle.json` file
- If the file is in the PR, schema validation will be executed and the check will succeed IF the bundled file matches the schema

**Comment by rajpalc7** [comment]
This ticket has been completed and tested locally on my machine but looks like we have a small blocker on OCABundle.json file and I have created a ticket - https://app.zenhub.com/workspaces/bcgov-ditp-enterprise-applications-team-63c987121278d5001ecb177b/issues/gh/bcgov/aries-oca-bundles/76 to solve this blocker. Once the blocker ticket is done, I will be able to create PR and push my local changes and mark this ticket as completed

**Comment by gethushan** [comment]
Nope @rajpalc7 

This issue in open state ....

If you want i can able to help you @esune 

We can able to create JSON action validator in GitHub workflow easily like my basic [repository](https://github.com/gethushan/JSON-Action.git)

**Comment by esune** [comment]
@rajpalc7 this is not done yet: #75 still needs to be reviewed and merged

**Comment by rajpalc7** [comment]
Hello @esune - The ticket is tested successfully locally on my machine . Waiting for @amanji or you to review and merge
