### ISSUE TITLE
Need all OCABundle.json files to validate against Schema.json File

### ISSUE THREAD

**Issue by rajpalc7** [bcgov/aries-oca-bundles#76]
Currently the OCA Bundle file in OCABundles/schema/bcgov-digital-trust/student-card and OCABundles/schema/qc_anig_demo/Attestation_numerique_didentite_gouvernemental  are not validating against Schema.json file.

"secondary_background_color"  needs to be added in Branding Overlay for OCABundles/schema/bcgov-digital-trust/student-card.

 "background_image_slice":  , "primary_attribute": and "secondary_attribute" needs to be added in Branding Overlay for OCABundles/schema/qc_anig_demo/Attestation_numerique_didentite_gouvernemental  to fix the validation.

**Comment by cvarjao** [comment]
@rajpalc7 , those attributes are optional not mandatory. Please adjust schema accordingly

**Comment by rajpalc7** [comment]
@cvarjao - Thanks for looking into this clecio, current issue is the OCABundle.json files in different folder seems to be different from each from each other. If I set schema according to one OCABundle file, it will fail for all the other 3 paths.

**Comment by amanji** [comment]
@rajpalc7  I think we can just keep `type` and `capture_base` for now and remove the other attributes from the `required` attributes

**Comment by rajpalc7** [comment]
@cvarjao - Thanks Clecio , Adjusted Schema according to the OCABundle.json files and workflow is running successfully now.
